# Generated by Django 5.2 on 2025-11-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0002_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="behaviors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="camera",
            name="latest_upload",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="location",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="camera",
            name="name",
            field=models.CharField(default="New Camera", max_length=255),
        ),
        migrations.AddField(
            model_name="camera",
            name="occurrences",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="camera",
            name="vehicles",
            field=models.IntegerField(default=0),
        ),
    ]
