# Generated by Django 5.2 on 2025-11-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0003_camera_behaviors_camera_latest_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="polygon",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]

# Generated by Django 5.2 on 2025-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0003_camera_behaviors_camera_latest_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="polygon",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
