# Generated by Django 5.2 on 2025-11-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0004_camera_polygon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="behaviors",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="latest_upload",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="occurrences",
        ),
        migrations.RemoveField(
            model_name="camera",
            name="vehicles",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=50, null=True)),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                ("calibration_points", models.JSONField(blank=True, default=list)),
                ("reference_points", models.JSONField(blank=True, default=list)),
                ("reference_distance_meters", models.FloatField(blank=True, null=True)),
                ("meter_per_pixel", models.FloatField(blank=True, null=True)),
                ("vehicles", models.IntegerField(default=0)),
                ("speeding_count", models.IntegerField(default=0)),
                ("swerving_count", models.IntegerField(default=0)),
                ("abrupt_stopping_count", models.IntegerField(default=0)),
                ("vehicle_breakdown", models.JSONField(blank=True, default=dict)),
                ("signs", models.IntegerField(default=0)),
                ("sign_classes", models.JSONField(blank=True, default=list)),
                ("sign_breakdown", models.JSONField(blank=True, default=dict)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="BrakePoint.camera",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
