# Generated by Django 5.2 on 2025-11-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "BrakePoint",
            "0005_remove_camera_behaviors_remove_camera_latest_upload_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="jeepney_hotspot",
            field=models.BooleanField(default=False),
        ),
    ]
