# Generated by Django 5.2 on 2025-11-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0006_video_jeepney_hotspot"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
