# Generated by Django 5.2 on 2025-11-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0007_video_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="maskrcnn_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="processing_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not Started"),
                    ("yolo", "YOLO Detection"),
                    ("mask-rcnn", "Mask R-CNN Detection"),
                    ("complete", "Complete"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="yolo_progress",
            field=models.IntegerField(default=0),
        ),
    ]
