# Generated by Django 5.2 on 2026-02-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0008_video_maskrcnn_progress_video_processing_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="behaviors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="camera",
            name="occurrences",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="camera",
            name="saved_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="BrakePoint.savedlocation",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="vehicles",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="camera",
            name="polygon",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
