# Generated by Django 5.2 on 2026-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0009_camera_behaviors_camera_occurrences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="calibration_points",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="camera",
            name="is_calibrated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="camera",
            name="meter_per_pixel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="reference_distance_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="camera",
            name="reference_points",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
