# Generated by Django 5.2 on 2026-02-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0010_camera_calibration_points_camera_is_calibrated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
