# Generated by Django 5.2.11 on 2026-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0011_add_camera_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="latest_upload",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="bounds",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedlocation",
            name="geometry",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
