# Generated by Django 5.2.11 on 2026-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0012_camera_latest_upload_savedlocation_bounds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedlocation",
            name="location_type",
            field=models.CharField(
                choices=[("aoi", "Area of Interest"), ("sub_area", "Sub Area")],
                default="sub_area",
                max_length=20,
            ),
        ),
    ]
