# Generated by Django 5.2.11 on 2026-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BrakePoint", "0013_savedlocation_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedlocation",
            name="parent_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
